# Context Root
server:
  servlet:
    context-path: /readbook

spring:
  mvc:
    static-path-pattern: "/static/**"
  web:
    resources:
      static-locations: "classpath:static/"
      add-mappings: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    properties:
      hibernate:
        ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/myDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vc100240

logging:
  level: debug
  com.callor.readbook: debug