#Context Path
server.servlet.context-path=/erp

# classpath : spring src/main 폴더를 가리키는 키워드
spring:
  mvc:
    static-path-pattern: /static/**
    web:
      resources:
        static-locations: classpath:static/
        add-mappings: true
  # logger Setting
  output.ansi.enabled: ALWAYS